#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="SF Pro"
PADDINGS=3

AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &

launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

bar=(
    height=38
    color=$BAR_COLOR
    border_width=2
    border_color=$BAR_BORDER_COLOR
    shadow=off
    position=top
    sticky=on
    padding_right=10
    padding_left=10
    y_offset=-5
    margin=0
    topmost=window
    color=0x00000000
    border_color=0x00000000
)

sketchybar --bar "${bar[@]}"

defaults=(
    updates=when_shown
    icon.font="$FONT:Regular:14.0"
    icon.color=$ICON_COLOR
    icon.padding_left=$PADDINS
    icon.padding_right=$PADDINGS
    label.font="$FONT:Semibold:13.0"
    label.color=$LABEL_COLOR
    label.padding_left=$PADDINGS
    label.padding_right=$PADDINGS
    label.shadow.drawing=on
    label.shadow.distance=2
    label.shadow.color=0xff000
    padding_right=$PADDINGS
    padding_left=$PADDINGS
    background.height=26
    background.corner_radius=9
    background.border_width=2
    popup.background.border_width=2
    popup.background.corner_radius=9
    popup.background.border_color=$POPUP_BORDER_COLOR
    popup.background.color=$POPUP_BACKGROUND_COLOR
    popup.blur_radius=20
    popup.background.shadow.drawing=off
    scroll_texts=on
)

sketchybar --default "${defaults[@]}"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
# brew install switchaudio-osx
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/audio_device.sh"

sketchybar --hotload on
sketchybar --update

echo "sketchybar configuation loaded.."
